### ISSUE TITLE
Proposal for help

### ISSUE THREAD

**Issue by ArtemK123** [zetroot/SafeHouseAMS#130]
Привет,
Наткнулся на твою [статью на хабре](https://habr.com/ru/post/549736/), с неё перешёл на гитхаб.
Меня заинтересовал твой репозиторий. Я был бы не против помочь в его разработке.
Сейчас идёт [hacktoberfest](https://hacktoberfest.digitalocean.com/). Я могу помочь в рамках этого мероприятия.
Если есть работа для меня - заводи issues и описывай, что нужно сделать. Я буду делать по мере возможности.

**Comment by zetroot** [comment]
@ArtemK123 большое спасибо за интерес к проекту! 
Он довольно слабо описан, поэтому меня даже удивило, что он заинтересовал случайного посетителя:)
Я не уверен, что могу придумать хороших задач для решения в рамках хактоберфеста. Но, будем на связи! Еще раз благодарю за внимание к проекту.
