### ISSUE TITLE
Сделать комменты необязательными

### ISSUE THREAD

**Issue by ArtemK123** [zetroot/SafeHouseAMS#163]
Сейчас на бэке любой публичный класс требует комментариев.
Исходя из предположения, что модули приложения не будут паблишиться как пакеты и использоваться в других проектах другими девами, я могу сказать следующие:
1. Комменты не нужны, ведь разработчик и так может подсмотреть всю нужную информацию в IDE
2. Комменты опасны, ведь после рефакторинга можно забыть их проапдейтить - и тогда они будут хранить ложную информацию
3. Комменты замедляют девелопмент
4. Комменты уменьшают читабельность кода

Исходя из выше описанного, я предлагаю сделать комменты необязательными.

**Comment by zetroot** [comment]
Нет.
Комменты обязательны и их надо поддерживать в актуальном состоянии. К этому надо прилагать усилия.

**Comment by ArtemK123** [comment]
А их будет читать кто-то, кто не имеет непостредственного доступа к репозиторию SafeHouseAMS?

**Comment by zetroot** [comment]
Я не понял вопрос.
Это проект с открытыми и свободными (в рамках лицензии) исходниками. Т.е  все имеют доступ как минимум на чтение.
Требование обязательной документации обязывает написать словами, что должен делать код, по мнению автора.

Xmldoc - это декларация о намерениях, и поддержание ее в актуальном состоянии это работа, которую надо делать. Может это не самый  лучший способ документирования, но более лучшие мне неизвестны;-)

**Comment by ArtemK123** [comment]
А что мешает вместо комментария прочитать собственно код?
Большинство комментариев выглядит примерно так:

<summary>Create entity</summary>
<params name=guid>Guid of an enitity</params>
<params name=description>Description of an entity</params>

public void Create(Guid guid, string description)

В таком случае, комментарий не добавляет никакой информации. Более того, он только мешает читать класс.
С другой стороны, если любой человек может прочитать коммент - то на каком языке его писать? Большинство комментариев на русском, но ведь их может читать человек, который русского не знает.
Ещё я вижу проблему в том, что корректность комментариев нельзя проверить никаким тестом. Если в пулл реквесте кто-то забыл поменять коммент, то это можно заметить только мануально во время ревью.

Исходя из написаного выше - я считаю, что лучший способ документирования - это сам код и тесты к нему.
